[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
votingsystemdapp = "cokJoPEvqS7hEA3D6KaiZur2gMhmyuAYzfU6xqifs3u"

[programs.devnet]
votingsystemdapp = "CfU2hH8HEy6UQhiEeECeJL66112N18EuYq1khpX2N1RF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
